project = 'ShootEmAll'
description = 'Arcade shooter with tower defense features.'
 new_type("macro","Macros")
file = {'level.lua','entity/entity.lua', 'entity/weapon.lua', 'entity/player.lua', 'entity/bullet.lua', 'entity/mob/mob.lua', 'entity/mob/bat.lua', 'entity/mob/mummy.lua'}
-- can specify the Markdown processor (falls back to markdown.lua)
format='discount'
-- if you don't use markdown you may wish for backticks to be
-- expanded if they enclose a reference.
backtick_references = true
plain=false